#pragma once

#include "Base/Base.h"

#include <QString>
#include <set>

class ComputeRegion : public Base
{
public:
    QString m_Name;
    bool m_Enabled = true;
    bool m_AutoGenerated = false;
    std::set<int> m_SourceSetIds;
    std::set<int> m_DirectNodeIds;
    std::set<int> m_DirectElementIds;
    std::set<int> m_NodeIds;
    std::set<int> m_ElementIds;

    bool ContainsNode(int nodeId) const;
    bool ContainsElement(int elementId) const;
    bool Overlaps(const ComputeRegion& other) const;
    void MergeFrom(const ComputeRegion& other);
};
