#pragma once

#include "Base/Base.h"

#include <QString>
#include <set>

// 定义参与一次计算的节点和单元区域。
class ComputeRegion : public Base
{
public:
    QString m_Name;                    // 区域显示名称
    bool m_Enabled = true;             // 是否参与求解
    bool m_AutoGenerated = false;      // 是否由程序自动生成
    std::set<int> m_SourceSetIds;      // 引用的模型集编号
    std::set<int> m_DirectNodeIds;     // 直接指定的节点编号
    std::set<int> m_DirectElementIds;  // 直接指定的单元编号
    std::set<int> m_NodeIds;           // 展开后的节点编号
    std::set<int> m_ElementIds;        // 展开后的单元编号

    bool ContainsNode(int nodeId) const; // 判断节点是否属于区域
    bool ContainsElement(int elementId) const; // 判断单元是否属于区域
    bool Overlaps(const ComputeRegion& other) const; // 判断两个区域是否相交
    void MergeFrom(const ComputeRegion& other); // 合并另一个区域的成员
};
